### ISSUE TITLE
Create a Variety of Simple Web3 Protocols/Apps

### ISSUE THREAD

**Issue by pynchmeister** [huff-language/huff-examples#7]
Based off of this repo: https://github.com/m1guelpf/lil-web3 , implement huff contract examples for each concept. These concepts include but may not be limited to DIY implementations of:

* ENS
* OpenSea
* Fractional
* Juicebox
* Gnosis Safe
* Flashloans
* Superfluid

**Comment by abigger87** [comment]
This should be a language-external repository, closing for now.
